//! # wasm-smtp-component
//!
//! WASM Component Model interface for [`wasm-smtp`].
//!
//! This crate exports the [`smtp-send`][`crate`] WIT interface defined in
//! `wit/smtp.wit`, allowing any language with WIT bindings to send email
//! through `wasm-smtp` without writing Rust.
//!
//! ## Building
//!
//! ```sh
//! # The wasm32-wasip2 target is all that is needed; it emits a
//! # Component Model component directly, without cargo-component.
//! cargo build --target wasm32-wasip2 -p wasm-smtp-component
//! # Output: target/wasm32-wasip2/debug/wasm_smtp_component.wasm
//! ```
//!
//! ## Running it
//!
//! Under any WASI 0.2 host. `tools/component-smoke` in this workspace is
//! one, and the gate runs it against every build.
//!
//! ## Running tests on native
//!
//! ```sh
//! cargo test -p wasm-smtp-component
//! ```
//!
//! ## Credential security
//!
//! Credentials cross the host-component boundary as plain WIT strings on
//! every `send` call. They are not retained by the component between calls.
//! See `docs/src/adapters/component-model.md` for the full threat model.
//!
//! [`wasm-smtp`]: https://docs.rs/wasm-smtp

// ── Trust anchors (RFC 030 D3) ────────────────────────────────────────────

// Parsed when an `smtp-config` is created, never at `send`. On native hosts
// only the unit tests reach it.
#[cfg_attr(not(target_arch = "wasm32"), allow(dead_code))]
mod trust;

// ── WIT bindings (wasm32 only) ────────────────────────────────────────────

// `#[allow(unsafe_code)]`: everything inside this module is generated by
// wit-bindgen. The canonical ABI lowering it emits is unsafe by construction.
// The crate lint stays at `deny`, so hand-written unsafe is still refused.
#[cfg(target_arch = "wasm32")]
#[allow(unsafe_code)]
mod bindings {
    wit_bindgen::generate!({
        path: "wit",
        world: "smtp-client",
        // Map every imported WASI interface onto the bindings the `wasi`
        // crate already provides, so the component carries one copy of them
        // rather than two. `wasm-smtp-wasi` does the actual socket work
        // through the same bindings.
        with: {
            "wasi:clocks/monotonic-clock@0.2.12": wasi::clocks::monotonic_clock,
            "wasi:io/error@0.2.12": wasi::io::error,
            "wasi:io/poll@0.2.12": wasi::io::poll,
            "wasi:io/streams@0.2.12": wasi::io::streams,
            "wasi:sockets/instance-network@0.2.12": wasi::sockets::instance_network,
            "wasi:sockets/ip-name-lookup@0.2.12": wasi::sockets::ip_name_lookup,
            "wasi:sockets/network@0.2.12": wasi::sockets::network,
            "wasi:sockets/tcp@0.2.12": wasi::sockets::tcp,
            "wasi:sockets/tcp-create-socket@0.2.12": wasi::sockets::tcp_create_socket,
        },
    });
}

// wit-bindgen 0.57 wires the export through the `export!` macro that
// `generate!` emits, rather than through an `exports:` key. `with_types_in`
// names the module the bindings were generated in. The macro expands to the
// `#[export_name]` shims the Component Model ABI requires, hence the second
// scoped allowance; a module is used because an attribute cannot be attached
// to a macro invocation directly.
#[cfg(target_arch = "wasm32")]
#[allow(unsafe_code)]
mod export_glue {
    use super::{SmtpSendImpl, bindings};
    bindings::export!(SmtpSendImpl with_types_in bindings);
}

// ── Type aliases (shared between wasm32 and native stubs) ─────────────────

#[cfg(target_arch = "wasm32")]
use bindings::exports::wasm_smtp::smtp::smtp_send::{
    Guest, GuestSmtpConfig, SendError, SendResult, SmtpConfig, SmtpConfigBorrow, SmtpCredentials,
    SmtpMessage, TlsMode, TrustAnchors,
};

/// Native-only stubs so the crate compiles and tests on non-WASM hosts.
#[cfg(not(target_arch = "wasm32"))]
mod stubs;

#[cfg(not(target_arch = "wasm32"))]
use stubs::{SendError, SendResult, SmtpCredentials, SmtpMessage, TlsMode, TrustAnchors};

// ── The `smtp-config` resource (RFC 030 D1) ───────────────────────────────

/// The validated contents of an `smtp-config` resource.
///
/// Built only by `validate`, which performs every check the configuration
/// gets, and immutable afterwards: the fields are private and nothing
/// writes them. `send` therefore never validates a configuration; it only
/// reads one.
#[cfg_attr(not(target_arch = "wasm32"), allow(dead_code))]
pub struct ConfigState {
    host: String,
    port: u16,
    ehlo_domain: String,
    tls_mode: TlsMode,
    /// `None` connects with the adapter's bundled roots; `Some` holds
    /// exactly the caller's trust anchors, which replace them.
    roots: Option<rustls::RootCertStore>,
}

#[cfg_attr(not(target_arch = "wasm32"), allow(dead_code))]
impl ConfigState {
    /// Check the arguments of `smtp-config.create` and build the state.
    ///
    /// The EHLO domain gets the core's existing check, the one a connection
    /// would otherwise apply; host and port have no checks of their own,
    /// and none are invented here. Trust anchors are parsed completely.
    /// Every rejection is `invalid-input` with a fixed message: neither
    /// check repeats its input.
    fn validate(
        host: String,
        port: u16,
        ehlo_domain: String,
        tls_mode: TlsMode,
        trust: &TrustAnchors,
    ) -> Result<Self, SendError> {
        wasm_smtp::protocol::validate_ehlo_domain(&ehlo_domain)
            .map_err(|e| SendError::InvalidInput(e.to_string()))?;
        let choice = match trust {
            TrustAnchors::Bundled => trust::Trust::Bundled,
            TrustAnchors::Custom(pem) => trust::Trust::Custom(pem),
        };
        let roots = trust::resolve(choice).map_err(|e| SendError::InvalidInput(e.to_string()))?;
        Ok(Self {
            host,
            port,
            ehlo_domain,
            tls_mode,
            roots,
        })
    }
}

#[cfg(target_arch = "wasm32")]
impl GuestSmtpConfig for ConfigState {
    fn create(
        host: String,
        port: u16,
        ehlo_domain: String,
        tls_mode: TlsMode,
        trust: TrustAnchors,
    ) -> Result<SmtpConfig, SendError> {
        Self::validate(host, port, ehlo_domain, tls_mode, &trust).map(SmtpConfig::new)
    }
}

// ── Synchronous driver for the async client (wasm32 only) ─────────────────

/// Drive a future to completion using a no-op waker.
///
/// The WIT `send` export is synchronous while [`wasm_smtp::SmtpClient`] is
/// async, so the component needs a way to run one future to completion. A
/// full executor would be dead weight here: every future this crate awaits
/// comes from `wasm-smtp-wasi`, whose transport polls WASI pollables inline
/// and therefore resolves on the first poll.
///
/// # Panics
///
/// Panics if the future returns `Poll::Pending`, which would mean the
/// transport started yielding and this assumption no longer holds.
#[cfg(target_arch = "wasm32")]
fn block_on<F: core::future::Future>(fut: F) -> F::Output {
    use core::pin::pin;
    use core::task::{Context, Poll, Waker};

    let waker = Waker::noop();
    let mut cx = Context::from_waker(waker);
    let mut fut = pin!(fut);
    match fut.as_mut().poll(&mut cx) {
        Poll::Ready(value) => value,
        Poll::Pending => panic!(
            "block_on: future returned Pending — the WASI transport is \
             expected to resolve on the first poll"
        ),
    }
}

// ── Core implementation ───────────────────────────────────────────────────

/// The struct that implements the `smtp-send` WIT interface.
pub struct SmtpSendImpl;

impl SmtpSendImpl {
    /// Core send logic, shared between the WIT export and native tests.
    ///
    /// Connects, authenticates, sends one message, and quits. A fresh TCP
    /// connection is used for every call; nothing is retained afterwards.
    // Takes credentials and message by value to match the native stand-in
    // below, whose signature the generated `Guest::send` fixes.
    #[allow(clippy::needless_pass_by_value)]
    #[cfg(target_arch = "wasm32")]
    pub fn send_impl(
        config: &ConfigState,
        credentials: SmtpCredentials,
        message: SmtpMessage,
    ) -> Result<SendResult, SendError> {
        // No configuration checks here: `ConfigState` can only exist once
        // `smtp-config.create` has accepted it (RFC 030 D1).
        //
        // `custom` anchors replace the adapter's roots entirely; `bundled`
        // leaves the adapter's default in place.
        let options = match &config.roots {
            Some(roots) => wasm_smtp_wasi::ConnectOptions::default().with_root_store(roots.clone()),
            None => wasm_smtp_wasi::ConnectOptions::default(),
        };

        // The two connect helpers are distinct async fns, so each one is
        // driven inside its own match arm rather than through a shared
        // future binding.
        let client_result = match config.tls_mode {
            TlsMode::Implicit => block_on(wasm_smtp_wasi::connect_smtps_with(
                &config.host,
                config.port,
                &config.ehlo_domain,
                options,
            )),
            TlsMode::Starttls => block_on(wasm_smtp_wasi::connect_smtp_starttls_with(
                &config.host,
                config.port,
                &config.ehlo_domain,
                options,
            )),
        };
        let mut client = client_result.map_err(smtp_error_to_wit)?;

        // Authenticate.
        block_on(client.login(&credentials.username, &credentials.password))
            .map_err(smtp_error_to_wit)?;

        // Send the message.
        let to_refs: Vec<&str> = message.to.iter().map(String::as_str).collect();
        let outcome = block_on(client.send_mail(&message.from, &to_refs, &message.raw_message))
            .map_err(smtp_error_to_wit)?;

        // QUIT (best-effort; ignore errors to not mask a successful send).
        block_on(client.quit()).ok();

        Ok(SendResult {
            reply_code: outcome.code,
        })
    }

    /// Native-host stand-in for [`Self::send_impl`].
    ///
    /// The component's socket layer exists only on `wasm32-wasip2`, so on a
    /// native host every call reports that instead of attempting a send.
    // Takes its arguments by value to match the wasm32 signature, which the
    // generated `Guest` trait fixes.
    #[allow(clippy::needless_pass_by_value)]
    #[cfg(not(target_arch = "wasm32"))]
    pub fn send_impl(
        config: &ConfigState,
        credentials: SmtpCredentials,
        message: SmtpMessage,
    ) -> Result<SendResult, SendError> {
        let _ = (&config, &credentials, &message);
        Err(smtp_error_to_wit(wasm_smtp::SmtpError::Io(
            wasm_smtp::IoError::new(
                "wasm-smtp-component only runs on wasm32-wasip2; \
                 use cargo test for native unit tests",
            ),
        )))
    }
}

// ── WIT Guest impl (wasm32 only) ──────────────────────────────────────────

#[cfg(target_arch = "wasm32")]
impl Guest for SmtpSendImpl {
    type SmtpConfig = ConfigState;

    fn send(
        config: SmtpConfigBorrow<'_>,
        credentials: SmtpCredentials,
        message: SmtpMessage,
    ) -> Result<SendResult, SendError> {
        Self::send_impl(config.get(), credentials, message)
    }
}

// ── Error mapping ─────────────────────────────────────────────────────────

fn smtp_error_to_wit(e: wasm_smtp::SmtpError) -> SendError {
    match e {
        wasm_smtp::SmtpError::Io(io) => SendError::Io(io.to_string()),
        wasm_smtp::SmtpError::Protocol(p) => SendError::Protocol(p.to_string()),
        wasm_smtp::SmtpError::Auth(_) => SendError::AuthRejected,
        wasm_smtp::SmtpError::InvalidInput(i) => SendError::InvalidInput(i.to_string()),
        wasm_smtp::SmtpError::Policy(p) => SendError::PolicyRejected(p.to_string()),
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn send_error_io_variant_carries_message() {
        let e = SendError::Io("connection refused".into());
        match e {
            SendError::Io(msg) => assert_eq!(msg, "connection refused"),
            _ => panic!("wrong variant"),
        }
    }

    #[test]
    fn send_error_auth_rejected_has_no_payload() {
        let e = SendError::AuthRejected;
        assert!(matches!(e, SendError::AuthRejected));
    }

    fn create(ehlo: &str, trust: &TrustAnchors) -> Result<ConfigState, SendError> {
        ConfigState::validate(
            "smtp.example.com".into(),
            465,
            ehlo.into(),
            TlsMode::Implicit,
            trust,
        )
    }

    fn generated_cert_and_key() -> (String, String) {
        let certified =
            rcgen::generate_simple_self_signed(vec!["ca.example".to_owned()]).expect("rcgen");
        (certified.cert.pem(), certified.signing_key.serialize_pem())
    }

    #[test]
    fn create_with_bundled_keeps_the_adapter_roots() {
        let cfg = create("client.example.com", &TrustAnchors::Bundled).expect("valid config");
        assert_eq!(cfg.host, "smtp.example.com");
        assert_eq!(cfg.port, 465);
        assert!(cfg.roots.is_none(), "bundled must not build a custom store");
    }

    #[test]
    fn create_with_custom_holds_exactly_those_roots() {
        let (cert, _) = generated_cert_and_key();
        let cfg = create("client.example.com", &TrustAnchors::Custom(cert)).expect("valid config");
        assert_eq!(cfg.roots.as_ref().map(rustls::RootCertStore::len), Some(1));
    }

    #[test]
    fn create_fails_when_a_second_certificate_is_indented() {
        // RFC 030 A1: an indented block is not a comment. Trusting only the
        // first certificate would be silent partial acceptance, so the
        // configuration must not be created at all.
        let (first, _) = generated_cert_and_key();
        let (second, _) = generated_cert_and_key();
        let mut indented = String::new();
        for line in second.lines() {
            indented.push(' ');
            indented.push_str(line);
            indented.push('\n');
        }
        let result = create(
            "client.example.com",
            &TrustAnchors::Custom(format!("{first}{indented}")),
        );
        assert!(
            matches!(result, Err(SendError::InvalidInput(_))),
            "create must fail, not trust one of two certificates"
        );
    }

    #[test]
    fn create_rejects_an_invalid_ehlo_domain_as_invalid_input() {
        let err = create("", &TrustAnchors::Bundled)
            .err()
            .expect("empty EHLO domain");
        assert!(matches!(err, SendError::InvalidInput(_)), "{err:?}");
    }

    #[test]
    fn create_rejects_a_private_key_without_echoing_it_or_falling_back() {
        let (_, key) = generated_cert_and_key();
        let err = create("client.example.com", &TrustAnchors::Custom(key.clone()))
            .err()
            .expect("a private key is not a trust anchor");
        let SendError::InvalidInput(message) = err else {
            panic!("expected invalid-input");
        };
        assert!(!message.contains("PRIVATE KEY"), "{message}");
        for line in key
            .lines()
            .filter(|l| !l.starts_with("-----") && !l.is_empty())
        {
            assert!(!message.contains(line), "{message}");
        }
    }

    #[test]
    fn smtp_message_to_is_vec() {
        let msg = SmtpMessage {
            from: "a@example.com".into(),
            to: vec!["b@example.com".into(), "c@example.com".into()],
            raw_message: "Subject: hi\r\n\r\nbody\r\n".into(),
        };
        assert_eq!(msg.to.len(), 2);
    }

    #[test]
    fn credentials_fields_accessible() {
        let cred = SmtpCredentials {
            username: "user@example.com".into(),
            password: "secret".into(),
        };
        assert_eq!(cred.username, "user@example.com");
        // password is accessible (it's a plain struct field) but must never
        // appear in any log, error, or debug output.
        assert!(
            !format!("{cred:?}").contains("secret"),
            "credentials must not appear in Debug output"
        );
    }
}
