//! Native-host type stubs.
//!
//! On `wasm32-wasip2` these types are generated by `wit-bindgen::generate!`.
//! On native hosts they are hand-written mirrors so that unit tests compile
//! and run without a WASM runtime.

/// How to establish TLS.
// Named by `ConfigState` on every target. On native hosts nothing constructs
// `Starttls`, not even the unit tests; on wasm32 the generated type is used.
#[allow(dead_code)]
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TlsMode {
    Implicit,
    Starttls,
}

/// Which certificate authorities to trust (RFC 030 D2).
// Constructed only by the native unit tests, for the same reason as `TlsMode`.
#[cfg_attr(not(test), allow(dead_code))]
#[derive(Debug, Clone)]
pub enum TrustAnchors {
    Bundled,
    Custom(String),
}

/// SMTP authentication credentials.
///
/// Intentionally does NOT implement `Debug` to prevent accidental logging.
#[derive(Clone)]
pub struct SmtpCredentials {
    pub username: String,
    pub password: String,
}

impl core::fmt::Debug for SmtpCredentials {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("SmtpCredentials")
            .field("username", &self.username)
            .field("password", &"[REDACTED]")
            .finish()
    }
}

/// A single SMTP message: envelope + body.
#[derive(Debug, Clone)]
pub struct SmtpMessage {
    pub from: String,
    pub to: Vec<String>,
    pub raw_message: String,
}

/// Successful send result.
#[derive(Debug, Clone)]
pub struct SendResult {
    pub reply_code: u16,
}

/// Error returned when the send operation fails.
#[derive(Debug, Clone)]
pub enum SendError {
    Io(String),
    Protocol(String),
    AuthRejected,
    InvalidInput(String),
    PolicyRejected(String),
}
