//! Executes the `wasm-smtp-component` artifact under a real host
//! (RFC 028 S1, RFC 030 S4).
//!
//! The component shipped from 0.14.0 without ever being instantiated;
//! RFC 028 added this harness to run it. It starts the scripted
//! TLS-terminated SMTP responder on loopback, runs the real artifact
//! against it, and asserts the transcript the responder recorded rather
//! than that a call returned `Ok`.
//!
//! ```text
//! cargo build --target wasm32-wasip2 -p wasm-smtp-component
//! cargo run -p wasm-smtp-component-smoke
//! ```
//!
//! `COMPONENT_WASM` overrides the artifact path.
//!
//! ## Cases
//!
//! RFC 030 gave the interface a trust-anchor choice, so the run's own CA
//! can now reach the guest and the success path is asserted end to end:
//!
//! - `custom-implicit` and `custom-starttls`: an `smtp-config` whose
//!   `custom` trust anchors hold exactly the run's CA. The send must
//!   succeed, and the transcript must be the one SMTP requires — the same
//!   assertions the adapter smoke test makes, from the shared library.
//! - `bundled-refused`: `bundled` trusts only the Mozilla roots, which did
//!   not sign the run's certificate. The handshake must be refused, with a
//!   certificate error, and no SMTP command may reach the responder.
//! - `private-key-create`: `create` given the run's private key as
//!   `custom` must fail with `invalid-input`, and the error, captured here
//!   on the host side, must contain nothing from the key.
//!
//! The guest is given `127.0.0.1` and a certificate carrying an IP SAN,
//! for the reason `tools/smoke` documents: resolving `localhost` inside a
//! guest can yield `::1` first, and that would make this a test of name
//! resolution order.

use std::net::{Ipv4Addr, SocketAddr, TcpListener};
use std::path::{Path, PathBuf};
use std::thread;
use std::time::{Duration, Instant};

use wasm_smtp_smoke::{
    Expected, Recording, check_refused, check_session, generate_cert, serve_implicit,
    serve_starttls, server_config,
};
use wasmtime::component::{Component, Linker, ResourceTable};
use wasmtime::{Config, Engine, Store};
use wasmtime_wasi::{WasiCtx, WasiCtxBuilder, WasiCtxView, WasiView};

// Bound against the component's own WIT, so the harness talks to the
// contract the crate publishes rather than a hand-written copy of it.
//
// `allow(missing_docs)`: everything in here is generated by wasmtime's
// bindgen, and the workspace lints require docs on public items.
#[allow(missing_docs)]
mod bindings {
    wasmtime::component::bindgen!({
        path: "../../crates/wasm-smtp-component/wit",
        world: "smtp-client",
    });
}

use bindings::SmtpClient;
use bindings::exports::wasm_smtp::smtp::smtp_send;

/// How long the responder waits for the guest to connect before giving up.
/// Generous, because a debug-build guest under a cold host is not fast.
const ACCEPT_TIMEOUT: Duration = Duration::from_secs(30);

/// The session the component is told to send.
const EXPECTED: Expected<'static> = Expected {
    ehlo: "component.example.com",
    from: "smoke@example.com",
    rcpt: "rcpt@example.org",
};

/// Host state: WASI plus the resource table the component model needs.
struct Host {
    ctx: WasiCtx,
    table: ResourceTable,
}

impl WasiView for Host {
    fn ctx(&mut self) -> WasiCtxView<'_> {
        WasiCtxView {
            ctx: &mut self.ctx,
            table: &mut self.table,
        }
    }
}

#[derive(Clone, Copy)]
enum Case {
    CustomImplicit,
    CustomStartTls,
    BundledRefused,
    PrivateKeyCreate,
}

impl Case {
    const ALL: [Case; 4] = [
        Case::CustomImplicit,
        Case::CustomStartTls,
        Case::BundledRefused,
        Case::PrivateKeyCreate,
    ];

    fn name(self) -> &'static str {
        match self {
            Case::CustomImplicit => "custom-implicit",
            Case::CustomStartTls => "custom-starttls",
            Case::BundledRefused => "bundled-refused",
            Case::PrivateKeyCreate => "private-key-create",
        }
    }
}

fn main() {
    let wasm = std::env::var("COMPONENT_WASM").map_or_else(
        |_| PathBuf::from("target/wasm32-wasip2/debug/wasm_smtp_component.wasm"),
        PathBuf::from,
    );
    if !wasm.exists() {
        eprintln!(
            "component-smoke: component not found at {}\nbuild it first: \
             cargo build --target wasm32-wasip2 -p wasm-smtp-component",
            wasm.display()
        );
        std::process::exit(2);
    }

    let mut failures = 0;
    for case in Case::ALL {
        match run_case(case, &wasm) {
            Ok(()) => println!("PASS  {}", case.name()),
            Err(e) => {
                println!("FAIL  {}: {e}", case.name());
                failures += 1;
            }
        }
    }
    if failures > 0 {
        eprintln!("component-smoke: {failures} case(s) failed");
        std::process::exit(1);
    }
}

fn run_case(case: Case, wasm: &Path) -> Result<(), String> {
    // A fresh certificate per case, so no case can pass on another's state.
    let (cert_pem, key_pem) = generate_cert()?;
    match case {
        Case::CustomImplicit => positive(wasm, false, &cert_pem, &key_pem),
        Case::CustomStartTls => positive(wasm, true, &cert_pem, &key_pem),
        Case::BundledRefused => refused(wasm, &cert_pem, &key_pem),
        Case::PrivateKeyCreate => private_key_create(wasm, &key_pem),
    }
}

/// `custom` holding the run's CA: the send succeeds with the full
/// transcript.
fn positive(wasm: &Path, starttls: bool, cert_pem: &str, key_pem: &str) -> Result<(), String> {
    let tls_mode = if starttls {
        smtp_send::TlsMode::Starttls
    } else {
        smtp_send::TlsMode::Implicit
    };
    let trust = smtp_send::TrustAnchors::Custom(cert_pem.to_owned());
    let (outcome, recording, responder) =
        with_responder(wasm, starttls, cert_pem, key_pem, tls_mode, &trust)?;

    responder.map_err(|e| {
        format!(
            "responder: {e}; send returned {outcome:?}; recorded {:?}",
            recording.commands()
        )
    })?;
    match outcome {
        Outcome::Ok(250) => {}
        other => {
            return Err(format!(
                "expected send to succeed with 250, got {other:?}; recorded {:?}",
                recording.commands()
            ));
        }
    }
    check_session(&recording, starttls, &EXPECTED)
}

/// `bundled` against the run's certificate: refused before any SMTP.
fn refused(wasm: &Path, cert_pem: &str, key_pem: &str) -> Result<(), String> {
    let (outcome, recording, _responder) = with_responder(
        wasm,
        false,
        cert_pem,
        key_pem,
        smtp_send::TlsMode::Implicit,
        &smtp_send::TrustAnchors::Bundled,
    )?;
    // A responder-side error is the expected outcome here: the guest hangs
    // up on it when the certificate does not validate. The recording is what
    // matters, and `check_refusal` decides.
    check_refusal(&outcome, &recording)
}

/// `create` with the run's private key as `custom`: `invalid-input`, and
/// nothing from the key in the message.
fn private_key_create(wasm: &Path, key_pem: &str) -> Result<(), String> {
    // No network for this case: it must fail before a connection could
    // exist, so the host permits none.
    let (mut store, client) = instantiate(wasm, None)?;
    let created = client
        .wasm_smtp_smtp_smtp_send()
        .smtp_config()
        .call_create(
            &mut store,
            "127.0.0.1",
            465,
            EXPECTED.ehlo,
            smtp_send::TlsMode::Implicit,
            &smtp_send::TrustAnchors::Custom(key_pem.to_owned()),
        )
        .map_err(|e| format!("smtp-config.create trapped: {e:?}"))?;
    let message = match created {
        Err(smtp_send::SendError::InvalidInput(message)) => message,
        Err(other) => return Err(format!("expected invalid-input, got {other:?}")),
        Ok(config) => {
            let _ = config.resource_drop(&mut store);
            return Err("a private key was accepted as a trust anchor".to_owned());
        }
    };
    check_no_echo(&message, key_pem)
}

/// What the component's `send` returned.
#[derive(Debug)]
enum Outcome {
    Ok(u16),
    Err(String),
}

/// Serve one scripted session on loopback while the component creates a
/// configuration and sends through it once.
fn with_responder(
    wasm: &Path,
    starttls: bool,
    cert_pem: &str,
    key_pem: &str,
    tls_mode: smtp_send::TlsMode,
    trust: &smtp_send::TrustAnchors,
) -> Result<(Outcome, Recording, Result<(), String>), String> {
    let listener = TcpListener::bind(SocketAddr::from((Ipv4Addr::LOCALHOST, 0)))
        .map_err(|e| format!("bind failed: {e}"))?;
    let port = listener
        .local_addr()
        .map_err(|e| format!("local_addr failed: {e}"))?
        .port();
    let responder = spawn_responder(listener, starttls, cert_pem, key_pem)?;

    let sent = create_and_send(wasm, port, tls_mode, trust);

    let (recording, responder_result) = responder
        .join()
        .map_err(|_| "responder thread panicked".to_owned())?;
    // The guest's failure is the more informative one when both fail: a
    // responder error usually means the guest never got far enough to talk.
    let outcome = sent.map_err(|e| {
        format!(
            "{e}\n--- responder ---\n{responder_result:?}\n--- recorded ---\n{:?}",
            recording.commands()
        )
    })?;
    Ok((outcome, recording, responder_result))
}

type Responder = thread::JoinHandle<(Recording, Result<(), String>)>;

/// One connection, one scripted session, on its own thread so the guest
/// can run while the responder talks. The listener does not block
/// indefinitely: a guest that never connects has to fail the case rather
/// than hang it.
fn spawn_responder(
    listener: TcpListener,
    starttls: bool,
    cert_pem: &str,
    key_pem: &str,
) -> Result<Responder, String> {
    let tls_config = server_config(cert_pem, key_pem)?;
    listener
        .set_nonblocking(true)
        .map_err(|e| format!("set_nonblocking failed: {e}"))?;
    Ok(thread::spawn(move || {
        let deadline = Instant::now() + ACCEPT_TIMEOUT;
        loop {
            match listener.accept() {
                Ok((sock, _)) => {
                    // Hand the accepted socket back to blocking mode; the
                    // responder is written against a blocking stream.
                    if let Err(e) = sock.set_nonblocking(false) {
                        return (
                            Recording::default(),
                            Err(format!("set_blocking failed: {e}")),
                        );
                    }
                    return if starttls {
                        serve_starttls(sock, tls_config)
                    } else {
                        serve_implicit(sock, tls_config)
                    };
                }
                Err(e) if e.kind() == std::io::ErrorKind::WouldBlock => {
                    if Instant::now() >= deadline {
                        return (
                            Recording::default(),
                            Err("the guest never connected".to_owned()),
                        );
                    }
                    thread::sleep(Duration::from_millis(20));
                }
                Err(e) => return (Recording::default(), Err(format!("accept failed: {e}"))),
            }
        }
    }))
}

/// Instantiate the component. `port` is the one loopback port it may
/// reach; `None` permits no network at all.
fn instantiate(wasm: &Path, port: Option<u16>) -> Result<(Store<Host>, SmtpClient), String> {
    let mut config = Config::new();
    config.wasm_component_model(true);
    let engine = Engine::new(&config).map_err(|e| format!("engine: {e:?}"))?;

    let component = Component::from_file(&engine, wasm)
        .map_err(|e| format!("loading the component failed: {e:?}"))?;

    let mut linker: Linker<Host> = Linker::new(&engine);
    // This is the step the version question rests on: it registers the
    // host's WASI implementation under the interface names the guest
    // imports. If the guest's `@0.2.12` imports cannot be satisfied by
    // what this wasmtime provides, instantiation fails here.
    //
    // It does not, and that is the finding. wasmtime 36's `wasi:*`
    // packages are at 0.2.6, while the artifact imports 0.2.12 (from the
    // `wasi` crate) and 0.2.3 (from the Rust standard library). One host
    // minor satisfies both, because a 0.2.x host is compatible across
    // the 0.2 line — which is why the world's declared minor is a
    // statement about where our bindings came from, not a requirement a
    // host has to match exactly.
    wasmtime_wasi::p2::add_to_linker_sync(&mut linker)
        .map_err(|e| format!("adding WASI to the linker failed: {e:?}"))?;

    // Loopback only, and only the responder's port. No inherited network,
    // no filesystem: the component needs neither.
    let mut builder = WasiCtxBuilder::new();
    builder.inherit_stderr();
    if let Some(port) = port {
        builder
            .allow_ip_name_lookup(true)
            .allow_tcp(true)
            .socket_addr_check(move |addr, _| {
                let allowed = addr.ip().is_loopback() && addr.port() == port;
                Box::pin(async move { allowed })
            });
    }
    let ctx = builder.build();

    let mut store = Store::new(
        &engine,
        Host {
            ctx,
            table: ResourceTable::new(),
        },
    );
    let client = SmtpClient::instantiate(&mut store, &component, &linker)
        .map_err(|e| format!("instantiating the component failed: {e:?}"))?;
    Ok((store, client))
}

/// Create a configuration, send one message through it, and drop it.
fn create_and_send(
    wasm: &Path,
    port: u16,
    tls_mode: smtp_send::TlsMode,
    trust: &smtp_send::TrustAnchors,
) -> Result<Outcome, String> {
    let (mut store, client) = instantiate(wasm, Some(port))?;
    let api = client.wasm_smtp_smtp_smtp_send();

    // Validated once, at creation (RFC 030 D1). A valid configuration must
    // be accepted in every case this function serves.
    let config = api
        .smtp_config()
        .call_create(
            &mut store,
            "127.0.0.1",
            port,
            EXPECTED.ehlo,
            tls_mode,
            trust,
        )
        .map_err(|e| format!("smtp-config.create trapped: {e:?}"))?
        .map_err(|e| format!("smtp-config.create rejected a valid configuration: {e:?}"))?;

    let credentials = smtp_send::SmtpCredentials {
        username: "smoke@example.com".to_owned(),
        password: "secret".to_owned(),
    };
    // A leading-dot line, so the responder can prove the component
    // dot-stuffed on the wire rather than trusting that it does.
    let message = smtp_send::SmtpMessage {
        from: EXPECTED.from.to_owned(),
        to: vec![EXPECTED.rcpt.to_owned()],
        raw_message: "From: smoke@example.com\r\n\
                      To: rcpt@example.org\r\n\
                      Subject: component smoke\r\n\
                      \r\n\
                      first line\r\n\
                      .leading-dot\r\n\
                      last line\r\n"
            .to_owned(),
    };

    let sent = api
        .call_send(&mut store, config, &credentials, &message)
        .map_err(|e| format!("the call trapped: {e:?}"))?;

    // The configuration outlives the send, as a borrow should allow, and is
    // released explicitly.
    config
        .resource_drop(&mut store)
        .map_err(|e| format!("dropping smtp-config failed: {e:?}"))?;

    Ok(match sent {
        Ok(result) => Outcome::Ok(result.reply_code),
        Err(e) => Outcome::Err(format!("{e:?}")),
    })
}

/// Assert the component refused a certificate it could not chain, and did
/// so properly.
///
/// Three things, and the third is the one a weaker test would miss: a
/// component that skipped validation would have completed the handshake
/// and spoken SMTP to a server holding a certificate signed by nobody.
fn check_refusal(outcome: &Outcome, rec: &Recording) -> Result<(), String> {
    let code = match outcome {
        Outcome::Ok(code) => {
            return Err(format!(
                "send succeeded with reply code {code} against an untrusted \
                 certificate; the component did not validate it. Recorded: {:?}",
                rec.commands()
            ));
        }
        Outcome::Err(e) => e,
    };

    // The refusal has to be about the certificate, not about a port that
    // was never opened or a name that did not resolve.
    let lowered = code.to_lowercase();
    if !["certificate", "handshake", "unknownissuer"]
        .iter()
        .any(|needle| lowered.contains(needle))
    {
        return Err(format!(
            "send failed, but not with a certificate error: {code}"
        ));
    }

    // And nothing may have been spoken over a channel that was never
    // authenticated. The same assertion the adapter smoke test's untrusted
    // mode and the tokio adapter's refused case make, from the shared
    // library; implicit TLS, so nothing at all is allowed.
    check_refused(rec, false, EXPECTED.ehlo)
        .map_err(|e| format!("no SMTP command may cross an unvalidated channel: {e}"))?;

    Ok(())
}

/// Assert an error message contains nothing from a private key: no line of
/// its PEM, no 16-character run of its base64, and not its label.
fn check_no_echo(message: &str, key_pem: &str) -> Result<(), String> {
    for line in key_pem.lines().filter(|l| !l.trim().is_empty()) {
        if message.contains(line) {
            return Err(format!("the error repeats a line of the key: {message}"));
        }
    }
    let body: String = key_pem
        .lines()
        .filter(|l| !l.starts_with("-----"))
        .collect();
    for window in body.as_bytes().windows(16) {
        let window = std::str::from_utf8(window).map_err(|_| "key PEM is not ASCII")?;
        if message.contains(window) {
            return Err(format!("the error repeats key material: {message}"));
        }
    }
    if message.contains("PRIVATE KEY") {
        return Err(format!("the error repeats the key's label: {message}"));
    }
    Ok(())
}

// ── Self-tests for the checkers ───────────────────────────────────────────
//
// `check_refusal` and `check_no_echo` are the assertions of two of the four
// cases, so each is shown failing on inputs chosen to be the ways it could be
// wrong. A checker that cannot fail passes every run and means nothing. The
// positive cases' assertions are `check_session`, self-tested in the shared
// library.
#[cfg(test)]
mod tests {
    use super::{Outcome, check_no_echo, check_refusal};
    use wasm_smtp_smoke::{Leg, Recording};

    fn recording(lines: &[&str]) -> Recording {
        Recording {
            lines: lines.iter().map(|l| (Leg::Tls, (*l).to_owned())).collect(),
            body: String::new(),
        }
    }

    /// The failure that matters: validation was skipped and the send went
    /// through. A harness that only asserted "it ran" would pass here.
    #[test]
    fn a_successful_send_is_a_failure() {
        let e = check_refusal(&Outcome::Ok(250), &recording(&["EHLO x", "QUIT"])).unwrap_err();
        assert!(e.contains("did not validate"), "{e}");
    }

    /// Failing is not enough; it has to fail for the right reason. A
    /// refused connection or an unresolved name would otherwise be
    /// indistinguishable from a rejected certificate.
    #[test]
    fn the_wrong_error_is_a_failure() {
        let e = check_refusal(
            &Outcome::Err("Io(\"connection refused\")".to_owned()),
            &recording(&[]),
        )
        .unwrap_err();
        assert!(e.contains("not with a certificate error"), "{e}");
    }

    /// And nothing may have been said over a channel that was never
    /// authenticated, even if the send ultimately failed.
    #[test]
    fn speaking_before_the_refusal_is_a_failure() {
        let e = check_refusal(
            &Outcome::Err("Io(\"TLS handshake failed: UnknownIssuer\")".to_owned()),
            &recording(&["EHLO component.example.com"]),
        )
        .unwrap_err();
        assert!(e.contains("no SMTP command may cross"), "{e}");
    }

    /// The shape a correct run has, so the three tests above are known to
    /// be rejecting something a passing input does not trip.
    #[test]
    fn a_certificate_refusal_with_an_empty_transcript_passes() {
        check_refusal(
            &Outcome::Err(
                "Io(\"TLS handshake failed: invalid peer certificate: UnknownIssuer\")".to_owned(),
            ),
            &recording(&[]),
        )
        .unwrap();
    }

    const KEY: &str = "-----BEGIN PRIVATE KEY-----\n\
                       MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgevZzL1gdAFr88hb2\n\
                       -----END PRIVATE KEY-----\n";

    /// Each way a message could leak the key is caught, and a fixed message
    /// passes.
    #[test]
    fn check_no_echo_catches_every_kind_of_leak() {
        assert!(check_no_echo("trust anchors: block 1: not a certificate", KEY).is_ok());
        assert!(check_no_echo("bad input: -----BEGIN PRIVATE KEY-----", KEY).is_err());
        assert!(check_no_echo("near AMBMGByqGSM49AgEG here", KEY).is_err());
        assert!(check_no_echo("a PRIVATE KEY was given", KEY).is_err());
    }
}
