//! Executes the `wasm-smtp-component` artifact under a real host
//! (RFC 028 S1).
//!
//! The component has shipped since 0.14.0 and, until this harness, had
//! never run. It was compiled for `wasm32-wasip2` and its packaged
//! contents were checked, but nothing ever instantiated it or called its
//! `smtp-send.send` export. Everything known about its behaviour came
//! from reading it.
//!
//! This harness closes that gap the same way `tools/smoke` closed it for
//! the WASI adapter: start the scripted TLS-terminated SMTP responder on
//! loopback, run the real thing against it, and assert the transcript the
//! responder recorded rather than that a call returned `Ok`.
//!
//! ```text
//! cargo build --target wasm32-wasip2 -p wasm-smtp-component
//! cargo run -p wasm-smtp-component-smoke
//! ```
//!
//! `COMPONENT_WASM` overrides the artifact path.
//!
//! ## What this asserts, and what it cannot
//!
//! The component builds its TLS trust anchors from the WASI adapter's
//! defaults — the bundled Mozilla root set — and `smtp-config` has no
//! field for a trust anchor: it carries host, port, EHLO domain, and TLS
//! mode, and nothing else. A run-generated CA therefore cannot reach the
//! guest through the interface, so a scripted responder with a self-signed
//! certificate cannot complete a handshake with it.
//!
//! What that leaves is the negative property, which is the one worth
//! having anyway: the component instantiates under a real host, its
//! `smtp-send.send` export runs end to end, it reaches the network,
//! validates the server certificate, refuses one it cannot chain, and
//! reports the refusal as a well-formed `send-error` rather than trapping,
//! hanging, or succeeding. That is the same property RFC 025's `untrusted`
//! smoke mode proves for the adapter, now proven through the component's
//! own export.
//!
//! Asserting the full positive transcript needs a decision about the
//! interface or the build; see the RFC 028 review request.
//!
//! The guest is given `127.0.0.1` and a certificate carrying an IP SAN,
//! for the reason `tools/smoke` documents: resolving `localhost` inside a
//! guest can yield `::1` first, and that would make this a test of name
//! resolution order.

use std::net::{Ipv4Addr, SocketAddr, TcpListener};
use std::path::PathBuf;
use std::sync::mpsc;
use std::thread;
use std::time::Duration;

use wasm_smtp_smoke::{Recording, check_refused, generate_cert, serve_implicit, server_config};
use wasmtime::component::{Component, Linker, ResourceTable};
use wasmtime::{Config, Engine, Store};
use wasmtime_wasi::{WasiCtx, WasiCtxBuilder, WasiCtxView, WasiView};

// Bound against the component's own WIT, so the harness talks to the
// contract the crate publishes rather than a hand-written copy of it.
//
// `allow(missing_docs)`: everything in here is generated by wasmtime's
// bindgen, and the workspace lints require docs on public items.
#[allow(missing_docs)]
mod bindings {
    wasmtime::component::bindgen!({
        path: "../../crates/wasm-smtp-component/wit",
        world: "smtp-client",
    });
}

use bindings::SmtpClient;
use bindings::exports::wasm_smtp::smtp::smtp_send;

/// How long the responder waits for the guest to connect before giving up.
/// Generous, because a debug-build guest under a cold host is not fast.
const ACCEPT_TIMEOUT: Duration = Duration::from_secs(30);

/// The domain the component is told to announce.
const EHLO: &str = "component.example.com";

/// Host state: WASI plus the resource table the component model needs.
struct Host {
    ctx: WasiCtx,
    table: ResourceTable,
}

impl WasiView for Host {
    fn ctx(&mut self) -> WasiCtxView<'_> {
        WasiCtxView {
            ctx: &mut self.ctx,
            table: &mut self.table,
        }
    }
}

fn main() {
    match run() {
        Ok(()) => println!("PASS  component"),
        Err(e) => {
            println!("FAIL  component: {e}");
            std::process::exit(1);
        }
    }
}

fn run() -> Result<(), String> {
    let wasm = std::env::var("COMPONENT_WASM").map_or_else(
        |_| PathBuf::from("target/wasm32-wasip2/debug/wasm_smtp_component.wasm"),
        PathBuf::from,
    );
    if !wasm.exists() {
        return Err(format!(
            "component not found at {}\nbuild it first: \
             cargo build --target wasm32-wasip2 -p wasm-smtp-component",
            wasm.display()
        ));
    }

    let (cert_pem, key_pem) = generate_cert()?;
    let tls_config = server_config(&cert_pem, &key_pem)?;

    let listener = TcpListener::bind(SocketAddr::from((Ipv4Addr::LOCALHOST, 0)))
        .map_err(|e| format!("bind failed: {e}"))?;
    let port = listener
        .local_addr()
        .map_err(|e| format!("local_addr failed: {e}"))?
        .port();

    // One connection, one scripted session, on its own thread so the guest
    // can run while the responder talks.
    // The listener does not block indefinitely: if the guest never connects
    // — which is what a component that failed before reaching the network
    // would do — the harness has to fail rather than hang.
    listener
        .set_nonblocking(true)
        .map_err(|e| format!("set_nonblocking failed: {e}"))?;

    let (tx, rx) = mpsc::channel();
    let responder = thread::spawn(move || {
        let deadline = std::time::Instant::now() + ACCEPT_TIMEOUT;
        let outcome = loop {
            match listener.accept() {
                Ok((sock, _)) => {
                    // Hand the accepted socket back to blocking mode; the
                    // responder is written against a blocking stream.
                    if let Err(e) = sock.set_nonblocking(false) {
                        break (
                            Recording::default(),
                            Err(format!("set_blocking failed: {e}")),
                        );
                    }
                    break serve_implicit(sock, tls_config);
                }
                Err(e) if e.kind() == std::io::ErrorKind::WouldBlock => {
                    if std::time::Instant::now() >= deadline {
                        break (
                            Recording::default(),
                            Err("the guest never connected".to_owned()),
                        );
                    }
                    thread::sleep(std::time::Duration::from_millis(20));
                }
                Err(e) => break (Recording::default(), Err(format!("accept failed: {e}"))),
            }
        };
        let _ = tx.send(());
        outcome
    });

    let call_result = call_send(&wasm, port, &cert_pem);

    let _ = rx.recv_timeout(std::time::Duration::from_secs(30));
    let (recording, responder_result) = responder
        .join()
        .map_err(|_| "responder thread panicked".to_owned())?;

    // The guest's failure is the more informative one when both fail: a
    // responder error usually means the guest never got far enough to talk.
    let outcome = call_result.map_err(|e| {
        format!(
            "{e}\n--- responder ---\n{:?}\n--- recorded ---\n{:?}",
            responder_result,
            recording.commands()
        )
    })?;

    // A responder-side error is the expected outcome here: the guest hangs
    // up on it when the certificate does not validate. The recording is what
    // matters, and `check` decides.
    let _ = responder_result;

    check(&outcome, &recording)
}

/// What the component's `send` returned.
enum Outcome {
    Ok(u16),
    Err(String),
}

/// Instantiate the component and call `smtp-send.send` once.
fn call_send(wasm: &PathBuf, port: u16, ca_pem: &str) -> Result<Outcome, String> {
    let mut config = Config::new();
    config.wasm_component_model(true);
    let engine = Engine::new(&config).map_err(|e| format!("engine: {e:?}"))?;

    let component = Component::from_file(&engine, wasm)
        .map_err(|e| format!("loading the component failed: {e:?}"))?;

    let mut linker: Linker<Host> = Linker::new(&engine);
    // This is the step the version question rests on: it registers the
    // host's WASI implementation under the interface names the guest
    // imports. If the guest's `@0.2.12` imports cannot be satisfied by
    // what this wasmtime provides, instantiation fails here.
    //
    // It does not, and that is the finding. wasmtime 36's `wasi:*`
    // packages are at 0.2.6, while the artifact imports 0.2.12 (from the
    // `wasi` crate) and 0.2.3 (from the Rust standard library). One host
    // minor satisfies both, because a 0.2.x host is compatible across
    // the 0.2 line — which is why the world's declared minor is a
    // statement about where our bindings came from, not a requirement a
    // host has to match exactly.
    wasmtime_wasi::p2::add_to_linker_sync(&mut linker)
        .map_err(|e| format!("adding WASI to the linker failed: {e:?}"))?;

    // Loopback only, and the CA the responder is using. No inherited
    // network, no filesystem: the component needs neither.
    let ctx = WasiCtxBuilder::new()
        .inherit_stderr()
        .allow_ip_name_lookup(true)
        .allow_tcp(true)
        .socket_addr_check(move |addr, _| {
            let allowed = addr.ip().is_loopback() && addr.port() == port;
            Box::pin(async move { allowed })
        })
        .build();

    let mut store = Store::new(
        &engine,
        Host {
            ctx,
            table: ResourceTable::new(),
        },
    );

    let bindings = SmtpClient::instantiate(&mut store, &component, &linker)
        .map_err(|e| format!("instantiating the component failed: {e:?}"))?;

    let config = smtp_send::SmtpConfig {
        host: "127.0.0.1".to_owned(),
        port,
        ehlo_domain: EHLO.to_owned(),
        tls_mode: smtp_send::TlsMode::Implicit,
    };
    let credentials = smtp_send::SmtpCredentials {
        username: "smoke@example.com".to_owned(),
        password: "secret".to_owned(),
    };
    // A leading-dot line, so the responder can prove the component
    // dot-stuffed on the wire rather than trusting that it does.
    let message = smtp_send::SmtpMessage {
        from: "smoke@example.com".to_owned(),
        to: vec!["rcpt@example.org".to_owned()],
        raw_message: "From: smoke@example.com\r\n\
                      To: rcpt@example.org\r\n\
                      Subject: component smoke\r\n\
                      \r\n\
                      first line\r\n\
                      .leading-dot\r\n\
                      last line\r\n"
            .to_owned(),
    };

    // The trust anchor has to reach the guest somehow, and the WIT has no
    // field for it: `smtp-config` carries host, port, EHLO domain, and TLS
    // mode only. The component builds its root store from the adapter's
    // defaults — the bundled Mozilla set — so a run-generated CA cannot be
    // injected through the interface. Recorded here because it shapes what
    // this harness can assert; see the review request.
    let _ = ca_pem;

    match bindings
        .wasm_smtp_smtp_smtp_send()
        .call_send(&mut store, &config, &credentials, &message)
        .map_err(|e| format!("the call trapped: {e:?}"))?
    {
        Ok(result) => Ok(Outcome::Ok(result.reply_code)),
        Err(e) => Ok(Outcome::Err(format!("{e:?}"))),
    }
}

/// Assert the component refused a certificate it could not chain, and did
/// so properly.
///
/// Three things, and the third is the one a weaker test would miss: a
/// component that skipped validation would have completed the handshake
/// and spoken SMTP to a server holding a certificate signed by nobody.
fn check(outcome: &Outcome, rec: &Recording) -> Result<(), String> {
    let code = match outcome {
        Outcome::Ok(code) => {
            return Err(format!(
                "send succeeded with reply code {code} against an untrusted \
                 certificate; the component did not validate it. Recorded: {:?}",
                rec.commands()
            ));
        }
        Outcome::Err(e) => e,
    };

    // The refusal has to be about the certificate, not about a port that
    // was never opened or a name that did not resolve.
    let lowered = code.to_lowercase();
    if !["certificate", "handshake", "unknownissuer"]
        .iter()
        .any(|needle| lowered.contains(needle))
    {
        return Err(format!(
            "send failed, but not with a certificate error: {code}"
        ));
    }

    // And nothing may have been spoken over a channel that was never
    // authenticated. The same assertion the adapter smoke test's untrusted
    // mode and the tokio adapter's refused case make, from the shared
    // library; implicit TLS, so nothing at all is allowed.
    check_refused(rec, false, EHLO)
        .map_err(|e| format!("no SMTP command may cross an unvalidated channel: {e}"))?;

    Ok(())
}

// ── Self-tests for the checker ────────────────────────────────────────────
//
// `check` is the whole assertion of this harness, so it gets the same
// treatment the things it guards get: it is shown failing, on inputs
// chosen to be the ways it could be wrong. A checker that cannot fail
// passes every run and means nothing.
//
// These cover the three properties from synthetic inputs; the end-to-end
// demonstration is in the RFC 028 review request, where a build that
// trusted the responder's certificate produced exactly the first case
// below against a live responder.
#[cfg(test)]
mod tests {
    use super::{Outcome, check};
    use wasm_smtp_smoke::{Leg, Recording};

    fn recording(lines: &[&str]) -> Recording {
        Recording {
            lines: lines.iter().map(|l| (Leg::Tls, (*l).to_owned())).collect(),
            body: String::new(),
        }
    }

    /// The failure that matters: validation was skipped and the send went
    /// through. A harness that only asserted "it ran" would pass here.
    #[test]
    fn a_successful_send_is_a_failure() {
        let e = check(&Outcome::Ok(250), &recording(&["EHLO x", "QUIT"])).unwrap_err();
        assert!(e.contains("did not validate"), "{e}");
    }

    /// Failing is not enough; it has to fail for the right reason. A
    /// refused connection or an unresolved name would otherwise be
    /// indistinguishable from a rejected certificate.
    #[test]
    fn the_wrong_error_is_a_failure() {
        let e = check(
            &Outcome::Err("Io(\"connection refused\")".to_owned()),
            &recording(&[]),
        )
        .unwrap_err();
        assert!(e.contains("not with a certificate error"), "{e}");
    }

    /// And nothing may have been said over a channel that was never
    /// authenticated, even if the send ultimately failed.
    #[test]
    fn speaking_before_the_refusal_is_a_failure() {
        let e = check(
            &Outcome::Err("Io(\"TLS handshake failed: UnknownIssuer\")".to_owned()),
            &recording(&["EHLO component.example.com"]),
        )
        .unwrap_err();
        assert!(e.contains("no SMTP command may cross"), "{e}");
    }

    /// The shape a correct run has, so the three tests above are known to
    /// be rejecting something a passing input does not trip.
    #[test]
    fn a_certificate_refusal_with_an_empty_transcript_passes() {
        check(
            &Outcome::Err(
                "Io(\"TLS handshake failed: invalid peer certificate: UnknownIssuer\")".to_owned(),
            ),
            &recording(&[]),
        )
        .unwrap();
    }
}
