[book]
title = "wasm-smtp"
authors = ["nabbisen <nabbisen@scqr.net>"]
description = "SMTP client crates for WebAssembly runtimes."
language = "en"
src = "src"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/nabbisen/wasm-smtp"
edit-url-template = "https://github.com/nabbisen/wasm-smtp/edit/main/docs/{path}"
